### ISSUE TITLE
Updating firmware 

### ISSUE THREAD

**Issue by MaluNoPeleke** [zvldz/vacuum#13]
How to update to a new firmware release?
I am currently on 1910 Valetudo RE and would like to update to the latest 2008 version without starting from scratch. 
Is that possible?

**Comment by zvldz** [comment]
Yes.
You can update via Valetudo.
Settings/Info/Firmware update - > [send request]
Example data:
url : https://vacuumz.info/download/gen2/vacuum_valetudo_re_2008.pkg
md5: cec5d20afb189e119b164ceb5324d058

**Comment by MaluNoPeleke** [comment]
Thanks, that worked easily.
Now the only issue is the new SSH key

Key exchange was not finished, connection is closed.
Cannot negotiate, proposals do not match.
