### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by dipcore** [zvldz/vacuum#3]
there is a typo in _LIST_CUSTUM_FUNCTION_ variable name

**Comment by zvldz** [comment]
Thanks for the message, could you describe in more detail where the typo.

**Comment by dipcore** [comment]
yep, https://github.com/zvldz/vacuum/search?q=LIST_CUSTUM_FUNCTION&unscoped_q=LIST_CUSTUM_FUNCTION

**Comment by zvldz** [comment]
Thanks. Fixed [#2982341](https://github.com/zvldz/vacuum/commit/2982341dcae6f3d8dbdc2e06fba779ee2f0efd23) .
