### ISSUE TITLE
Basic Example

### ISSUE THREAD

**Issue by florian-asche** [zvldz/vacuum#4]
Hi, 

why not add an basic example with which the user can start. 

Thanks, Florian

**Comment by florian-asche** [comment]
./builder_vacuum.sh --run-custom-script=ALL --replace-adbd --enable-appproxy-patcher --enable-addon --dnsserver=192.168.0.3 --enable-history --ntpserver=192.168.178.1 --enable-turn-off-ny --disable-logs --disable-firmware-updates --replace-miio --soundfile=../de.pkg --public-key=../authorized_keys --timezone=Europe/Berlin --valetudo-re-path=../valetudo/ --firmware ../v11_001898.fullos.a5a3abad-09c1-4285-88c9-9640ec7b3e88.pkg

**Comment by zvldz** [comment]
You can use vacuum*.sh scripts as examples.

**Comment by zvldz** [comment]
Closed #4
