### ISSUE TITLE
No Apt-Get in ready-built-firmwares > v1998?

### ISSUE THREAD

**Issue by willchr** [zvldz/vacuum#42]
Hi,

I just installed an ready-built-firmware with firmware 2008 and valetudo 5.3 and after installing it turned out not to have apt-get installed on the robo.

Older firmwares doesn't have this issue.

Is there a reason for that? Can I install apt-get afterwards anyhow? dpkg isn't installed neither...  

Christian

**Comment by zvldz** [comment]
Since version 2008, the firmware is no longer full ubuntu, but cutted os.
Somewhere I read that somebody tried to add apt themselves and it kind of worked.

**Comment by willchr** [comment]
After searching a couple of hour I give up for the moment. If you find the article once again it would be nice if u could share it here...
In the past I installed python and alsasound in order to let the robo speak, so maybe there is another possibility to integrate these applications before flashing?

**Comment by zvldz** [comment]
Valetudo Telegram group
https://t.me/joinchat/AR1z8xOGJQwkApTulyBx1w
![apt](https://user-images.githubusercontent.com/45265234/86444845-12c63380-bd1a-11ea-953d-2a502095f0a4.png)
[to-extract-from-root-with-tar-xhzvf.gz](https://github.com/zvldz/vacuum/files/4868427/to-extract-from-root-with-tar-xhzvf.gz)

What packages did you install exactly ?
There's a sox already installed to play the sound.

**Comment by willchr** [comment]
Thank you very much!!

Having sox would be fine actually, but it doesn't seem being installed in my pkg with fw 2020 and valetudoRe9.6.
"man sox" doesn't work the same as "play" and "sox" don't work.

**Comment by zvldz** [comment]
If you build the firmware yourself, you should add the option --enable-addon-sox.
The sox is installed in the ready-made firmware.

**Comment by willchr** [comment]
hhm, strange, I didn't build it on my own.....
Maybe downloaded from another source...?.... Will download/install it again and see... thx for the moment!!!!

**Comment by zvldz** [comment]
Closed #42
