### ISSUE TITLE
Built firmware with oucher

### ISSUE THREAD

**Issue by corentingosselin** [zvldz/vacuum#47]
Hey really nice tool,

I need it for oucher but I think you did not upload it yet ?
I tried to build myself, on mac os seems not working 🈂️ 

thanks !

**Comment by zvldz** [comment]
Ready-made firmware does not contain 'oucher'.
I didn't decide to add it there by default.
Firmware cannot be built on macos.

**Comment by corentingosselin** [comment]
thanks for your answer, just downloaded the virtual machine ;)

**Comment by zvldz** [comment]
Closed #47
