### ISSUE TITLE
Firmware build installation 

### ISSUE THREAD

**Issue by corentingosselin** [zvldz/vacuum#48]
Hello back:)

I built my firmware on linux:

<img width="1052" alt="Capture d’écran 2020-08-26 à 20 58 10" src="https://user-images.githubusercontent.com/8132994/91344926-ea6d2980-e7de-11ea-9d5c-0e99b7258b89.png">

Then I uploaded it:

<img width="1329" alt="Capture d’écran 2020-08-26 à 20 57 10" src="https://user-images.githubusercontent.com/8132994/91344963-f6f18200-e7de-11ea-8ba7-46d1a616a497.png">

The result:

<img width="1432" alt="Capture d’écran 2020-08-26 à 20 57 21" src="https://user-images.githubusercontent.com/8132994/91344980-fbb63600-e7de-11ea-9812-f0f61228041b.png">

the current build is an old build I tried with dustbuilder, this is not your vacuum build 
Also no files added, for example oucher.yml,oucher.conf, ect

Thanks for help

All text code:
https://hastebin.com/eyezadawuz.coffeescript

**Comment by zvldz** [comment]
For some reason, the new firmware was not installed. Although the robot accepted it for installation.
Try resetting the robot to the factory settings and then reinstall the new firmware.

Or you can try to install the firmware again and look at the logs here /mnt/data/rockrobo/rrlog.
There may be a reason why the firmware is not installed.

**Comment by corentingosselin** [comment]
Thank you so much, with factory reset, works like a charm !

**Comment by corentingosselin** [comment]
Just small question, do you think is it possible to customize greeting sound ?

**Comment by zvldz** [comment]
It seems that the file 
/opt/rockrobo/resources/sounds/power_on.wav 
or 
/opt/rockrobo/resources/sounds/start_greeting.wav
 is responsible for this

**Comment by zvldz** [comment]
Closed #48
