### ISSUE TITLE
Password is not "cleaner"?

### ISSUE THREAD

**Issue by Demolux** [zvldz/vacuum#49]
Hi,

I flashed "vacuum_4018_valetudo_re_0_9_8.pkg" onto the Mi vacuum V1 and I cannot ssh into it with password "cleaner" and

`sudo ssh root@192.168.X.Y`

(the IP is correct)

Have you may changed the PW or is it another user?

Thanks!

**Comment by zvldz** [comment]
Password did not change (cleaner). I can't check it myself, I have s50. But nobody complained.

**Comment by Demolux** [comment]
Hm. Thanks for the answer though, its not a problem for running Valetudo, I was just wondering. Appreciate your work, Regards
