### ISSUE TITLE
where to find change_root_pass.sh

### ISSUE THREAD

**Issue by mpagels** [zvldz/vacuum#51]
I´ve used vacuum_builder.sh to update my S5 roborock to v.0.6.1 and connected with ssh to the vacuum to change the password. I found a vacuum.txt with the information to run a script

`RUN - /root/run.d/change_root_pass.sh`

but found no .sh file in /root

Where can I find the sh file?

**Comment by zvldz** [comment]
The file is created during firmware generation and deleted after execution.
https://github.com/zvldz/vacuum/blob/67f05cc4d47798758626fc96b90e7fb87f8277e7/custom-script/custom_vacuum.sh#L102

**Comment by zvldz** [comment]
Closed #51
