### ISSUE TITLE
pkg file of new version of valetudo for roborock S50

### ISSUE THREAD

**Issue by Mib68** [zvldz/vacuum#57]
Hi,

I saw that it's a new relase of Valetudo 2021.01.0b0 it's possible to make the .pkg file for the roborock s 50 with this new version of Valetudo ?

Thanks a lot

Bye

**Comment by zvldz** [comment]
Yes, I did, it worked.
I thought about waiting for release, but I'll do it tomorrow.

**Comment by zvldz** [comment]
Created images with Valetudo 2021.01.0b0.

**Comment by Mib68** [comment]
Thanks a lot
