### ISSUE TITLE
disable-logs

### ISSUE THREAD

**Issue by florian-asche** [zvldz/vacuum#6]
Hi,

the log disable function would be better if you remove the file in rsyslog.d directory. Then i can still send the logs to my remote location.

Regards,
Florian

**Comment by florian-asche** [comment]
The filename is 50-default.conf

**Comment by zvldz** [comment]
Thanks. I will check how best to do. Sorry for answering for a long time, rarely does anyone write here.

**Comment by zvldz** [comment]
I can rename all files in /etc/rsyslog.d/ when building the firmware. Would it be so suitable ?
